### ISSUE TITLE
Анализатор кода съедает шаблонные параметры типа, при наведении на его поле

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#100]
```
type
  t0<T> = class
    
    a: T;
    
  end;

begin end.
```
При наведении на `a` видим:
![image](https://user-images.githubusercontent.com/27270190/55010546-08809a00-4fed-11e9-8318-17805f68ed83.png)

А правильно:
`var t0<T>.a: T`

Потому что если шаблонных параметров несколько - так будет лучше видно какой из них используется для типа `a`.

**Comment by ibond84** [comment]
Так задумывалось. Это сокращенная запись.

**Comment by SunSerega** [comment]
А где так лучше?

**Comment by miks1965** [comment]
Вот как в студии
![изображение](https://user-images.githubusercontent.com/10325391/55832871-2b4b9c00-5b1f-11e9-9921-29659147235f.png)
Возможно, у нас это какие-то технические ограничения интеллисенса

**Comment by SunSerega** [comment]
Вряд ли, к примеру так:
![image](https://user-images.githubusercontent.com/27270190/55833583-89c54a00-5b20-11e9-801d-018f50317bf7.png)

Возвращаемое значение показывает как byte, то есть шаблонный параметр анализатор кода помнит.

Считая что говорит @ibond84 - это выглядит как непродуманная фича.
