### ISSUE TITLE
Элементы управления в палитре в режиме проекта Windows Forms слипаются 

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [pascalabcnet/pascalabcnetide#105]
![image](https://user-images.githubusercontent.com/42812113/56375471-4cdb1080-620e-11e9-954b-2aea9c38ba22.png)

Я понимаю, что серьезных исправлений ждать в области дизайнера форм не стоит. Но мелкие - почему бы и нет?

**Comment by miks1965** [comment]
Согласен. В дизайнере форм многое надо делать в связи с High DPI.

Но вот Sun Serega активно на форумах никому не советует им пользоваться. Может, выкусить его?

**Comment by EmilyGraceSeville7cf** [comment]
> Может, выкусить его?

Согласен. Именно это я и предложил [здесь](http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/1212?u=mrfresnel).

**Comment by miks1965** [comment]
Вам бы всё ломать ))

**Comment by EmilyGraceSeville7cf** [comment]
В связи с нуждой использования дизайнера форм прошу доделать для High DPI. Прописывать код интерфейса ручками - это не дело.

**Comment by miks1965** [comment]
Это хорошее дело. Может, кто-то кроме меня тоже возьмётся посмотреть этот код.
