### ISSUE TITLE
Показывает подсказку по точке для комментария

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#106]
```
begin
  
  //ToDo integer
  
  
  {integer}
  
end.
```
![image](https://user-images.githubusercontent.com/27270190/56473952-54532180-647b-11e9-8984-7e60f4b2dcb1.png)

![image](https://user-images.githubusercontent.com/27270190/56473963-6cc33c00-647b-11e9-9c8c-67d0e92ea843.png)

В первом случае обязательно должно быть ToDo в комментарии чтоб воспроизвести. А для `{}` комментария и это не нужно.

**Comment by AIexandrKotov** [comment]
Не todo, а любое слово. todo вообще ничем не отличается, просто подсвечивается.
![image](https://user-images.githubusercontent.com/44296606/56504950-eb26e900-6522-11e9-9a71-55ace05f919e.png)

**Comment by EmilyGraceSeville7cf** [comment]
![image](https://user-images.githubusercontent.com/42812113/56652201-7e7f2c00-6693-11e9-9f62-4e5271e6e9c9.png)

Подсказка показывается для последнего в строке слова, являющегося названием базового типа. Также замечу, что для пользовательских типов не воспроизводится.

**Comment by ibond84** [comment]
Ничего страшного. Пусть показывает. Иначе придется бегать до начала файла, чтобы понять нет ли там начала комментария.
