### ISSUE TITLE
Ctrl+Delete в редакторе не работает

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnetide#109]
https://www.youtube.com/watch?v=5MhyyE8ywEQ

**Comment by miks1965** [comment]
А почему он должен работать? У меня тоже не работает

**Comment by AIexandrKotov** [comment]
Это скорее enhancement. Не работает, ибо не реализовано. А должно удалять правый кусок слова от курсора (так же, как Ctrl+Backspace, но в другую сторону)

Если подскажете где в проекте это можно добавить — сам попробую сделать.

**Comment by miks1965** [comment]
Не подскажу - не знаю. Редактор не наш. Его исходники лежат в отдельной папке - поищите.

Тему закрываю - это мелочёвка, на которую команда разработчиков не может себе позволить тратить силы.
