### ISSUE TITLE
Показывать индексы элементов перечислимого типа в метаданных

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnetide#117]
Так выглядит enum ConsoleKey в метаданных Visual Studio:
![image](https://user-images.githubusercontent.com/44296606/57980175-16243000-7a30-11e9-94f3-934a971735bc.png)

А так в метаданных PascalABC.NET:
![image](https://user-images.githubusercontent.com/44296606/57980181-32c06800-7a30-11e9-8fc2-fd277503196c.png)

**Comment by miks1965** [comment]
А уверены, что они показываются даже если идут подряд с нуля?

**Comment by AIexandrKotov** [comment]
В Visual Studio показываются:
![image](https://user-images.githubusercontent.com/44296606/57986914-7db79b00-7a83-11e9-8691-ef588229e8ba.png)

![image](https://user-images.githubusercontent.com/44296606/57986915-84dea900-7a83-11e9-86b7-eb21042154ca.png)

**Comment by EmilyGraceSeville7cf** [comment]
Идея хороша (мне нравится), но не стоит ли посмотреть на другие IDE для Pascal прежде чем вносить изменения? Повторяю: у нас не Visual Studio и не C#, в частности, а Pascal, хоть и являющийся .NET языком. Таким образом, хотелось бы увидеть аргументы помимо «а вот так в Visual Studio».

**Comment by miks1965** [comment]
Мне тоже не вполне это нравится. Enum - это не целые числа, хотя при использовании флагов в некотором смысле могут так трактоваться. Я бы если и делал целые, то только если enumы не упорядочены с нуля и далее.

**Comment by AIexandrKotov** [comment]
Обновил Pull Request.
