### ISSUE TITLE
Ctrl+клик не работает для имени, если перед ним стоит ^

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#119]
```
begin
  var i: integer;
  var p: ^integer;
end.
```
Если зажать `Ctrl` - на `integer` можно тыкнуть, откроется его описание.
А с `^integer` то же самое не работает.

**Comment by miks1965** [comment]
Ну да - это другой тип

**Comment by SunSerega** [comment]
1. Когда в файле на, уже, почти тысячу строк надо перейти к определению типа, которое закопано в противоположной части файла:
![image](https://user-images.githubusercontent.com/27270190/58193467-b8ac0f80-7ccb-11e9-960b-99edc41f1941.png)
Получается очень неудобно, что Ctrl+клик не работает.

А то что вы сказали - это принцип ради принципа, от которого страдают удобства.

2. Как вы так же можете видеть на скрине - при наведении на `^CommandQueueInfoType` показывается именно определение `CommandQueueInfoType`, а не `^CommandQueueInfoType`, что правильно и удобно. Раз это работает так - значит и Ctrl+клик должен работать так же.

**Comment by EmilyGraceSeville7cf** [comment]
> Раз это работает так - значит и Ctrl+клик должен работать так же.

А что на счёт других IDE для других диалектов Pascal? Что там происходит в данном случае?

**Comment by ibond84** [comment]
Посмотрел в делфи, там ctrl+click вообще работает, только если класс находится в другом файле. Типа в самом файле навигация не нужна... Какие-то там не от мира сего.
