### ISSUE TITLE
Некоторые имена из System отсутствуют в Ctrl+Space при "uses System"

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#122]
```
uses System;

begin
  var i: UInt32;
end.
```
По наведению показывает описание, но.

Но если поставить курсор после имени и нажать Ctrl+Space - его там нет. Ну и на пустом месте это тоже сломано.

Список имён с которыми это сломано:
```
SByte

Int16
UInt16

Int32
UInt32
```
То есть, по сути все имени целых чисел. Только `byte`, и `[u]int64` уже есть в `PABCSystem`.

Возможно, это сломано и для других имён, я проверил только самые основные.

**Comment by miks1965** [comment]
А что делает cTRL-Space после имени?

**Comment by SunSerega** [comment]
Даёт имена из обычного Ctrl+Space, но показывает только те что начинаются с имени - после которого его тыкнули. В данном случае он не видит ни 1 имени начинающегося с `UInt32` - поэтому и список вообще не показывает.

**Comment by ibond84** [comment]
И думаю, правильно не показывает. Для этого есть стандартные паскалевские типы. Показывает только, если писать System.
