### ISSUE TITLE
Анализатор кода ломается после закрытия и открытия проекта wf

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#128]
https://youtu.be/7v-kibpfZ1g

До и после перезагрузки я сначала нажимал Ctrl+Space, а затем набирал `self.`.

До перезагрузки - в Ctrl+Space и в `self.` показывало всё что должно.

А после неё - в Ctrl+Space остались только ключевые слова, а в `self.` осталось только содержимое `Form1`, всё что было унаследовано от `Form` - пропало.

**Comment by miks1965** [comment]
Заметьте, что дизайнер форм здесь ни при чём. Это - анализатор кода.

**Comment by SunSerega** [comment]
Это происходит только в проектах wf.

**Comment by miks1965** [comment]
Надо выяснить причину. Сами по себе эти проекты не отличаются от других. 

Еще раз повторю - проекты с подключенными dll для Windows Forms с багами в дизайнере не имеют ничего общего

**Comment by SunSerega** [comment]
А, только сейчас понял что вы говорили про название issue...

**Comment by ibond84** [comment]
Ну надо четко называть issue: интеллисенс ломается при открытии проекта по двойному щелчку.

**Comment by ibond84** [comment]
тест
