### ISSUE TITLE
Лямбду добавляет в список глобальных имён, при чём 8 раз

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#131]
Случайно наткнулся, запуская программу котова, которую он на форуме запостил:
```
begin
  'Йнснб'.Select(x -> Succ(x)).Print;
end.
```
![image](https://user-images.githubusercontent.com/27270190/60528266-bc847600-9cfc-11e9-8aac-69006b502079.png)

**Comment by AIexandrKotov** [comment]
```
begin
 ''.Select(x -> x);
end.
```
![image](https://user-images.githubusercontent.com/44296606/60528747-d6728880-9cfd-11e9-8d77-6aa4303889ca.png)
