### ISSUE TITLE
Неверное описание для inc()

### ISSUE THREAD

**Issue by developer46i** [pascalabcnet/pascalabcnetide#132]
Я заметил интересную особенность, написав код:

    begin
    var a:word:=1;
    inc(a);
    write(a);
    end.

на что, при наведении на функцию inc(), был выведен комментарий:
![image](https://user-images.githubusercontent.com/52495777/60591229-afbc5c80-9da6-11e9-800f-12e3cc87290d.png)

хотя у нас a имеет тип данных word, а в описании у нас символьный тип данных.  Такое же сообщение  есть и для longword, uint64, shortint, smallint, int64.  
Для  integer описание верное:  
![image](https://user-images.githubusercontent.com/52495777/60591283-d1b5df00-9da6-11e9-8648-64539c78abbe.png)

и для char:  
![image](https://user-images.githubusercontent.com/52495777/60591293-d8445680-9da6-11e9-9c41-8e3ecd4fb5b3.png)

Для byte в описании применен перечислимый тип данных:  
![image](https://user-images.githubusercontent.com/52495777/60591323-e8f4cc80-9da6-11e9-96c2-fa1915425bdc.png)

Просьба:
Обеспечить правильный вывод описания над вышеописанными типами данных.
Спасибо за чтение сообщения до конца!

**Comment by AIexandrKotov** [comment]
А теперь по-нормальному.
```
///- переопределённое описание
procedure p(var i: System.Enum) := exit;
///--
procedure p(var i: word) := exit;

begin
  var i: word := 0;
  p(i); //показывает переопределённое описание
end.
```

При сокрытии описание не должно показываться вообще. Даже если есть не сокрытые перегрузки, конкретно эта должна прятаться.

**Comment by developer46i** [comment]
Тогда понятно, спасибо! Также по такому же принципу получается и с функцией sin()?
![image](https://user-images.githubusercontent.com/52495777/60673276-13668880-9e80-11e9-9b4a-2409c94f795d.png)

**Comment by SunSerega** [comment]
А зачем `Sin` для `integer`? Радианы в нём всё равно не представишь...

**Comment by developer46i** [comment]
Логично, Синус в радианах: sin (45) = 0.850903524534118, но аргументом целое число может быть (про что я и говорю), в описании же число a представлено как вещественное.  Поэтому вопрос: здесь, в функции sin() показывается переопределенное описание, как и с функцией inc(), описанной выше?
Возможно ли сделать так, чтобы в описании функции показывался именно тот тип данных, который имеет переменная a?

**Comment by AIexandrKotov** [comment]
Нет, аргументом здесь вещественное число. integer к real неявно приводится. И писать об этом в описании бред. Это создавать для каждого типа function Sin(a: T) := Sin(a); Для целых числовых типов есть неявное приведение к real, это не ошибка.

**Comment by developer46i** [comment]
Спасибо, так и думал, Вы подтвердили. Я и не утверждал, что это ошибка. 
Но вернемся к inc(), где в качестве аргумента является word, longword, uint64, shortint, smallint, int64. Но здесь описание неверное, потому что число, например 9, не символ ('9'). Если мы увеличим код символа '9' на 1 то это будет кодировка символа ':' и по Юникоду, и по ASCII. Но мы увеличиваем число на 1, а не символ, поэтому хотим получить в результате 10. Поэтому неверно в данном случае описание: Увеличивает код символа с на 1.

**Comment by AIexandrKotov** [comment]
Там просто в PABCSystem не сделаны описания. Делать их муторно.
