### ISSUE TITLE
Анализатор кода отваливается, если в uses есть стандартное пространство имён в неправильном регистром

### ISSUE THREAD

**Issue by Nikita22007** [pascalabcnet/pascalabcnetide#136]
Если написать `Uses system;`, где  `system` с   маленькой  буквы, то  подсказки  по  нажатию не  работают

**Comment by AIexandrKotov** [comment]
![image](https://user-images.githubusercontent.com/44296606/61281504-29a30b80-a7d3-11e9-8895-164728751305.png)

всё работает, если не подтвердите информацию — issue закроют

**Comment by SunSerega** [comment]
И то точке тоже работает:

![image](https://user-images.githubusercontent.com/27270190/61293507-835c0380-a7dc-11e9-9eaf-4f87773a59eb.png)

Вы уверены что тестируете в последней версии? Сообщать баги в устаревшей версии бесполезно.

**Comment by Nikita22007** [comment]
![test](https://user-images.githubusercontent.com/41326310/61369324-85839800-a898-11e9-94d8-23c6e9eb86df.PNG)

**Comment by Nikita22007** [comment]
Если набрать с большой буквы, то все работает.
![Снимок](https://user-images.githubusercontent.com/41326310/61369412-b6fc6380-a898-11e9-8027-b67458e4e62e.PNG)

**Comment by SunSerega** [comment]
Мда, объясняете вы конечно ужасно...

Переименуйте issue в "Анализатор кода отваливается, если в uses есть стандартное пространство имён в неправильном регистром"

В Ctrl+Space в таком случае показывает только ключевые слова:
![image](https://user-images.githubusercontent.com/27270190/61402758-76bed480-a8dc-11e9-85b6-f3cb037a8882.png)

Однако по точке для типов он всё ещё работает:
![image](https://user-images.githubusercontent.com/27270190/61402938-dd43f280-a8dc-11e9-90d4-ca3b38779f0b.png)
И это касается и стандартных типов.

То есть сдохло всё глобальное из анализатора кода.
