### ISSUE TITLE
Intellisense не показывает константы класса из библиотеки по точке

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnetide#137]
```
library lib;

type
  T = class
    public const A = 1;
  end;

end.
```

![4](https://user-images.githubusercontent.com/44296606/61780495-110ea300-ae1c-11e9-9cb6-f42dac644920.png)

По наведению на T.A всё работает нормально.

**Comment by ibond84** [comment]
Это баг компилятора.

**Comment by AIexandrKotov** [comment]
Обращение по имени работало, поэтому и кинул в IDE-issue

**Comment by ibond84** [comment]
Ну, это я не в упрек. Просто интеллисенс не работал из-за бага в компиляторе, генерировавшем литеральное экземплярное поле.
