### ISSUE TITLE
Реализовать контекстные снипеты

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#138]
В данной ситуации:
```
begin
  if true then
    b|
end.
```
Если нажать Shift+Space - надо чтоб получалось следующее:
```
begin
  if true then
  begin
    |
  end;
end.
```
И, разумеется, это касается не только снипета `b`.

Это позволит автодополнению кода работать в паре со снипетами.

**Comment by ibond84** [comment]
Ну нажал Shift+Space, begin-end добавился. Эта фича была реализована много лет назад

**Comment by SunSerega** [comment]
Эту фичу подтвердил @miks1965. И автодополнением он занимается, так что не закрывайте сами.

**Comment by ibond84** [comment]
По Shift+Space я знаю только одни сниппеты: из template.pct И они работают. Либо создавайте понятный issue, либо все останется как есть.

**Comment by SunSerega** [comment]
Куда понятнее? Суть фичи автодополнения кода в том чтоб в зависимости от контекста - добавлялись/убирались отступы, `end`-ы и т.п.
Контекстые снипеты это интеграция снипетов и автодополнения кода, чтоб эти 2 фичи друг другу не мешали.

Admin сам назвал данную интеграцию - контекстными снипетами:
http://forum.mmcs.sfedu.ru/t/versiya-pascalabc-net-3-5/2959/83?u=sun_serega
А раз эта фича создана для него и по его же просьбе - главное чтоб понятно было ему.

**Comment by ibond84** [comment]
Ах понял. Это называется не какие-то узкие "контекстные сниппеты", а автоформатирование на лету, более общая и трудная задача.

**Comment by SunSerega** [comment]
Автоформатирование на лету уже есть, и в данной IDE называется автозавершением кода (первая кнопка в меню сервис).

А данная issue - про 1 из не реализованных частей этой фичи.

**Comment by ibond84** [comment]
Это не автоформатирование на лету. Автоформатирование на лету это когда нажимаешь точку с запятой или Enter, и вся строка или блок операторов форматируется автоматически.

**Comment by SunSerega** [comment]
И при чём к этому изменение отступов перед снипетом?

Та фича о которой вы говорите - большая, а изначальная идея была реализовать это как часть другой, уже более-менее доделанной фичи.

Хотя если у вас есть время и силы на полноценное автоформатирование на лету - я только за.
