### ISSUE TITLE
case, содержащий else без оператора - неправильно форматируется

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#146]
```
begin
  case 0 of
  else
  end;
end.
```
После 1 форматирования:
```
begin
  case 0 of
  else
    
  end ;
end.
```
После 2:
```
begin
  case 0 of
  else
  
    
  
  end ;
end.
```
То если тут добавляются лишние строчки между `else` и `end`, а после `end` ещё появляется лишний пробел.

Если добавить любой код после `else` - не воспроизводится.

**Comment by miks1965** [comment]
пофиксил

**Comment by SunSerega** [comment]
тут: https://github.com/pascalabcnet/pascalabcnet/commit/04ee19e0b79b312d50e33166a9d2c9eef938b279

Чтоб делать референс в другую репу - надо писать `pascalabcnet/pascalabcnetide#146`

**Comment by miks1965** [comment]
Ага, спасибо. Это долго

**Comment by SunSerega** [comment]
Не долго если копировать большую часть строчки из адреса 1 из репозиториев (если основного - ide дописать не сложно).
