### ISSUE TITLE
Анализатор кода для uses-in

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#151]
Пусть повисит тут пока не сделаете, чтоб сразу заметно было когда сделаете...

**Comment by miks1965** [comment]
Вы напишите-то, что сделать надо. Любой Issue должен иметь контент

**Comment by SunSerega** [comment]
```
uses u in '1\u.pas';

begin
  var a := new t1;
  p1;
end.
```
```
unit u;

type t1=class end;

procedure p1 := exit;

end.
```
[0.zip](https://github.com/pascalabcnet/pascalabcnetide/files/3541218/0.zip)

Это компилируется, но в программе ни `t1`, ни `p1` - анализатор кода не видит. Ну и собственно это не только классов и подпрограмм касается. Из модуля вообще ничего не видит, включая пространства имён `u`.

**Comment by SunSerega** [comment]
@ibond84 `Path.Combine` вроде не умеет обрабатывать `..\`, которые разрешены в `uses-in`.
Проверьте, пожалуйста, чтоб это тоже работало:
[0.zip](https://github.com/pascalabcnet/pascalabcnetide/files/3587493/0.zip)

**Comment by ibond84** [comment]
>вроде не умеет обрабатывать

умеет, конечно. все работает.

**Comment by SunSerega** [comment]
Странно, а у меня не умеет:
```
begin
  var path1 := 'abc\def';
  var path2 := '..\123.456';
  System.IO.Path.Combine(path1,path2).Println;
end.
```
![image](https://user-images.githubusercontent.com/27270190/64487379-738ff700-d242-11e9-94a9-5bec973fbf41.png)

**Comment by ibond84** [comment]
Ну, все умеет. Это валидный путь.

**Comment by SunSerega** [comment]
Нет, вы не поняли. `..\` в `uses-in` значит переход к предыдущей папке. А не тупое добавление как текста.

Вот `Path.Combine` может только добавлять текст. Вы использовали его, поэтому я сказал что это надо проверить отдельно.

**Comment by ibond84** [comment]
Ну, это работает. Я выше уже написал
