### ISSUE TITLE
.pcu файлы в папке с программой убивают анализатор кода для uses-in

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#159]
Особенно больно из за https://github.com/pascalabcnet/pascalabcnet/issues/2083.

[0.zip](https://github.com/pascalabcnet/pascalabcnetide/files/3681195/0.zip)

```
uses u in '1\u.pas';

begin
  // ни "u", ни "t1", ни "p1" не видит
  var o: u.t1;
  new t1;
  p1;
end.
```
```
unit u;

type
  t1 = class end;
  
procedure p1 := exit;

end.
```
Если положить `u.pcu` в корневую папку (где основная программа) и перезагрузить IDE - в основной программе перестанет видит имена из `u`.
В архиве выше `.pcu` файл уже лежит где надо.

**Comment by miks1965** [comment]
Да. Не кладите. В pcu впаян каталог. Если Вы его меняете - не работает

**Comment by SunSerega** [comment]
В смысле не класть?
1. Это может произойти случайно или при одноимённых модулях в разных папках.
2. Из за pascalabcnet/pascalabcnet#2083 компилятор сам кладёт, каждый раз ломая анализатор кода.

А чиниться анализатор кода только если полностью его перезапустить.
