### ISSUE TITLE
uses из implementation к текущему модулю моментально убивает IDE

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#165]
```
unit ___u___;

interface

implementation

uses ___u___;

end.
```
Подождите пока загрузится анализатор кода и наведите мышку на `___u___` на строчке с `uses`.
IDE моментально вылетает и даже не даёт сохраниться.

**Comment by AIexandrKotov** [comment]
не воспроизводится.

**Comment by SunSerega** [comment]
Только что собрал билд с последними коммитами мастера (то есть без своего фикса uses-in).
Всё ещё воспроизводится.

Win7x64

**Comment by AIexandrKotov** [comment]
А, да, воспроизводится, я забыл файл переименовать.
