### ISSUE TITLE
Убрать автоподстановку ; после := в ветке then

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnetide#167]
Убрать автоподстановку ; после := в ветке then

**Comment by SunSerega** [comment]
Тогда будет получатся такое:
```
begin
  if a then
    b()
  c();
end.
```
Это не лучше.

Как я [уже сказал](http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/1556?u=sun_serega) - правильно ставить `else` на строчке с оператором, тогда лишней `;` нету:
```
begin
  if a then
    b() else
  if c then
    d();
  e();
end.
```
Ну, если всё же хотите поддерживать синтаксис с `else if` на 1 строчке - надо убирать `;` при написании else на следующей строчке.

А не добавлять вообще - нельзя, потому что это ломает более общий случай.

P.S. кстати, а при чём тут `:=`? Если делать - то для всех операторов.

**Comment by miks1965** [comment]
> Ну, если всё же хотите поддерживать синтаксис с else if на 1 строчке - надо убирать ; при написании else на следующей строчке.

Ровно так и сделали
