### ISSUE TITLE
Intellisense - неверный тип ArrGen(10,i->i);

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnetide#168]
```
begin
  var a := ArrGen(10,i->i);
  a.
end.
```
При наведении на a выводит array of function(:): integer

**Comment by AIexandrKotov** [comment]
Это дубль https://github.com/pascalabcnet/pascalabcnetide/issues/59 и https://github.com/pascalabcnet/pascalabcnet/issues/1562

Ошибка очень старая. Было бы очень хорошо, если бы вы её исправили в этом году)

**Comment by ibond84** [comment]
пофиксено
