### ISSUE TITLE
Intellisence показывает неверный тип для i и не работает для Sum и Print

### ISSUE THREAD

**Issue by ProMix0** [pascalabcnet/pascalabcnetide#180]
[Задача](https://vk.com/away.php?utf=1&to=https%3A%2F%2Fgithub.com%2FNETMouse-projects%2FABCNET%2Fwiki%2FРабота-с-массивами) 5: 
```pascal 
{$reference ABCNET.dll} 
uses ABCNET.Utils; 
uses ABCNET.Extensions; 
begin 
  Arr.ReadInt32(Base.ReadInt32('N:'), 'Элемент {0}-ый:').Where((x, i) -> i mod 2 = 0).Sum().Println();
  // Intellisence показывает function(x: T; i: T): ; для i. 
  // Intellisence не работает для Sum и Println.
  Base.ReadChar(); 
end.
``` 
NETMouse projects (c)

**Comment by SunSerega** [comment]
Если уже постите сюда - желательно искать минимальный код. То есть кидать не весь код, а минимум для получения неправильного поведения.

**Comment by miks1965** [comment]
Закрыл эту Issue - опубликовал новую по мотивам

Просим вас выкладывать сюда ошибки и неточности с минимальным кодом без подключения dll.
