### ISSUE TITLE
Отладка неправильно показывает тип, если это имя есть в PABCSystem

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnetide#182]
![Ы331](https://user-images.githubusercontent.com/44296606/76246445-c88ee300-624e-11ea-9a37-b075d129c3e2.png)

Воспринимает класс word как PABCSystem.word

**Comment by miks1965** [comment]
Да, понятно.

Экранирование тут не нужно - word - это не ключевое слово

**Comment by AIexandrKotov** [comment]
а, точно...))
