### ISSUE TITLE
Сворачивание кода неправильно работает, улучшение сворачивания кода

### ISSUE THREAD

**Issue by Anonymous87549236** [pascalabcnet/pascalabcnetide#185]
1. http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/1926?u=just_name
Дальше цитирую http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/1933?u=just_name
2. > сворачивание выглядит коряво:
![image](https://user-images.githubusercontent.com/70477515/91662120-ff9ccd80-eae8-11ea-848f-66dd12eb58aa.png)

3. > Около **`end.`** присутствует окончание сворачивания кода, хотя остальной части нет:
![image](https://user-images.githubusercontent.com/70477515/91662183-5f937400-eae9-11ea-9fe7-459d3a2b3a8c.png)
4. > Думаю, что по аналогии с операторными скобками
![image](https://user-images.githubusercontent.com/70477515/91662219-ad0fe100-eae9-11ea-9a2f-4ee5800a9519.png)
следует изменить оформление сворачивания кода для префиксов
![image](https://user-images.githubusercontent.com/70477515/91662226-ba2cd000-eae9-11ea-9b87-bedd5439d2b0.png)
(убрать вторую кнопку сворачивания):
![image](https://user-images.githubusercontent.com/70477515/91662255-daf52580-eae9-11ea-85b1-1c1789f5137f.png)

**Comment by ibond84** [comment]
>2,3

Там синтаксически некорректная программа.
