### ISSUE TITLE
Ошибка после завершения отладки, во время которой был изменён исходный код отлаживаемой программы

### ISSUE THREAD

**Issue by Anonymous87549236** [pascalabcnet/pascalabcnetide#188]
Думаю, стоит запретить изменение исходного кода программы во время её отладки.
Как воспроизвести ошибку (цитата из http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/1933?u=just_name):

> Берём бесполезный код-пример:
> ```
> begin
>   Writeln('1132445');
>   var x:=ReadlnInteger;
>   Writeln(x*5+x);
>   loop 9 do x+=x*2;
> end.
> ```
> 1. Вставляем его в редактор IDE.
> 2. Отлаживая, доходим до середины:
> ![image](https://user-images.githubusercontent.com/70477515/91662847-a7b49580-eaed-11ea-8c68-503e7c49c3ee.png)
> 3. Вдруг хотим что-то изменить, не останавливая отладку (чтобы сработало, поменяю всё, скажем, на этот (https://pascalabcnet.github.io/mydoc_release_notes_3_7.html#в-ide-интегрирована-библиотека-nunit) пример):
> ![image](https://user-images.githubusercontent.com/70477515/91662867-c450cd80-eaed-11ea-84fa-dce5c4771e9d.png)
> 4. Теперь уже ничего не спасёт от ошибки “() : Не могу получить доступ к файлу ‘C:\PABCWork.NET\Output\Program1.exe – 4 System.UnauthorizedAccessException: Отказано в доступе по пути “C:\PABCWork.NET\Output\Program1.pdb”. в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) в System.IO.File.InternalDelete(String path, Boolean checkHost) в PascalABCCompiler.Compiler.Compile()’” и программы невозможно будет запустить, пока не перезагружу IDE:
> ![image](https://user-images.githubusercontent.com/70477515/91662885-e6e2e680-eaed-11ea-903f-98fb404240aa.png)

**Comment by SunSerega** [comment]
А по моему лучше уже странные ошибки, чем невозможность редактировать код.
Я часто добавляю комментарии типа `//ToDo` пока отлаживаю, когда замечаю что что то ещё не так.
