### ISSUE TITLE
SyntaxTreeNotEquals в TestRunner со свежим PABCSystem.pas в TestSuite\formatter_tests\input\

### ISSUE THREAD

**Issue by spectatorBH** [pascalabcnet/pascalabcnetide#194]
TestRunner выдает следующую ошибку, если обновить файл PABCSystem.pas (свежая версия взята из сборки 3.7.1-2677) в TestSuite\formatter_tests\input\:

```
***ERROR: check TestSuite/formatter_tests/output/log.txt:
SyntaxTreeNotEquals PascalABCCompiler.SyntaxTree.dot_question_node <...>\TestSuite\formatter_tests\input\PABCSystem.pas
```

**Comment by miks1965** [comment]
А при сборке инсталлята это видно?

Я запускаю инсталлят - и ошибок нет

**Comment by spectatorBH** [comment]
Сборка инсталлята у меня пока только удаленная и я не могу сейчас её надежно проверить, т.к. мне сначала надо будет сделать свежий клон официальной репы для более чистого эксперимента (сейчас там копия с массой моих изменений). Но если локально запускать оригинальный 'TestRunner 6' в копии из **свежескачанного zip-архива официальной репы**, сделав перед этим **обновление PABCSystem.pas в \TestSuite\formatter_tests\input** и добавив в **\bin все нужные dll-ки** для компиляции и форматирования (взятые из последнего офиц. инсталлята), то у меня получается вот что (все остальные тесты TestRunner'а проходят без ошибок):

![image](https://user-images.githubusercontent.com/21036474/92828205-6ec4cc80-f3db-11ea-8389-2b80c4ca1578.png)

Причем, без разницы в каком формате будет этот новый PABCSystem.pas -- 475 209 bytes (LF) или 488 671 (CR/LF) от 09.09.2020 -- первая ошибка в логе будет та же (SyntaxTreeNotEquals), остальные -- да, уже зависят от формата лайн-брейков. Проверено на свежей zip-копии с гитхаба от 10.09.2020 и dll-ках из офиц. v3.7.1-2683 от 09.09.2020 на Win10 x64 update 20H2:
```
CodeCompletion.dll		363.0 К	07.09.2020 18:55:04	--a-----
Compiler.dll			232.0 К	07.09.2020 18:55:04	--a-----
CompilerTools.dll		14.5 К	07.09.2020 18:55:02	--a-----
Errors.dll			8.5 К	07.09.2020 18:55:02	--a-----
ICSharpCode.NRefactory.dll	648.0 К	24.04.2019 20:16:58	--a-----
YieldHelpers.dll		4.5 К	07.09.2020 18:55:02	--a-----
Localization.dll		109.5 К	07.09.2020 18:55:02	--a-----
NETGenerator.dll		176.0 К	07.09.2020 18:55:04	--a-----
OptimizerConversion.dll		31.0 К	07.09.2020 18:55:10	--a-----
ParserTools.dll			134.0 К	07.09.2020 18:55:02	--a-----
PascalABCParser.dll		491.5 К	07.09.2020 18:55:10	--a-----
SemanticTree.dll		52.0 К	07.09.2020 18:55:02	--a-----
SyntaxTree.dll			500.0 К	07.09.2020 18:55:02	--a-----
SyntaxTreeConverters.dll	6.5 К	07.09.2020 18:55:04	--a-----
SyntaxVisitors.dll		114.5 К	07.09.2020 18:55:04	--a-----
TreeConverter.dll		884.0 К	07.09.2020 18:55:04	--a-----
```

**Comment by SunSerega** [comment]
> то у меня получается вот что (все остальные тесты TestRunner'а проходят без ошибок):

У меня в локальном репозитории тоже:

![image](https://user-images.githubusercontent.com/27270190/92889490-f2ec7380-f41e-11ea-8d44-68c281370365.png)

**Comment by miks1965** [comment]
А что вы запускаете что такое получается?

**Comment by SunSerega** [comment]
Обычный `_GenerateAllSetups.bat`.

Попробуйте заново клонировать всю свою репу в отдельную папку, чтоб она точно была чистая. И там запустить сборку проекта этим батником.

**Comment by spectatorBH** [comment]
@SunSerega А если записать свежий PABCSystem.pas в \TestSuite\formatter_tests\input перед запуском батника -- ошибки SyntaxTreeNotEquals у вас нет? Остальные ошибки в логе -- это другие проблемы форматтера, связанные именно с особенностями обработки LF-строк в тестовых файлах:

> Но с прогоном тестов в LF-формате еще остается актуальной проблема #196, которая в свою очередь скорее всего также связана с #195.

**Comment by SunSerega** [comment]
Нет, ошибку `SyntaxTreeNotEquals` не заметил.

**Comment by miks1965** [comment]
Прямо сейчас клонировал проект в чистую папку и запустил _GenerateAllSetups.bat

Всё работает

**Comment by spectatorBH** [comment]
@miks1965 Вы создали копию через git checkout или скачали zip? Данная проблема (а точнее, описанная конкретно в #196 и #195) проявляется только с файлами в LF-формате, т.е. строго в том виде, в котором они сейчас хранятся на гитхабе. Поэтому для верификации нужно скачать именно архив репозитория, а не клонировать утилитой git.

**Comment by spectatorBH** [comment]
> Нет, ошибку `SyntaxTreeNotEquals` не заметил.

@SunSerega Странно, я вот ради проверки закинул сейчас в \TestSuite\formatter_tests\input еще несколько объемных дополнительных файлов со сложной структурой кода, и вот результат (ошибки SyntaxTreeNotEquals не зависят от типа лайн-брейков исходных файлов!):

![image](https://user-images.githubusercontent.com/21036474/92993789-2a315200-f4fd-11ea-97f1-f5d2695768f1.png)

Т.е. появилось уже **2 подтипа** ошибок: `PascalABCCompiler.SyntaxTree.dot_question_node` и `PascalABCCompiler.SyntaxTree.double_question_node`.

**Comment by SunSerega** [comment]
А по вашему `git` может менять переносы строк? Я вообще то именно им скачивал.
Менять переносы строк любят редакторы. А гит скачивает как есть.

**Comment by SunSerega** [comment]
> и вот результат

А, возможно я первый раз пропустил потому что у меня, почему то, к строкам меседжбокса добавляет кучу ненужных переносов строк. Ещё раз запустил и вот:

![image](https://user-images.githubusercontent.com/27270190/92994227-3cad8a80-f501-11ea-9782-c35a72d311e9.png)

**Comment by miks1965** [comment]
Мы конечно же не скачиваем zip как вы понимаете. Это какой-то странный способ для разработчиков.

Если проблема в гитхабе, то я закрываю этот Issue - он имеет отношение к гитхабу, но не к нашему проекту

**Comment by SunSerega** [comment]
Вообще я только что сказал что скачивал гитом (а точнее через ssh.exe из папки бинарников гита) и у меня всё воспроизводится... Я ведь не так много пишу, можно и всё прочитать, а не только то что в глаза бросается.

**Comment by miks1965** [comment]
А у Вас раньше всё собиралось а сейчас не собирается?

**Comment by SunSerega** [comment]
У меня никогда нормально не собиралось. Но раньше весь лог 6-ой стадии забивался ошибками неправильных переносов строк (которые вы недавно исправили), поэтому эти ошибки видно не было. И я и котов об этих ошибках очень давно говорили. Вы это игнорили, поэтому мы стали игнорить 6-ую стадию тестировщика.

А может у вас как то по-особому настроена студия или ещё что то связанное со сборкой? Потому что я в настройках студии практически ничего не менял. И у спектатора, по сути, чистая система (я сомневаюсь что гитхаб менял бы настройки, это сделало бы много проектов не совместимыми со сборкой на стороне гитхаба).

**Comment by miks1965** [comment]
Не знаю. У нас на разных компьютерах всё собирается. От Студии там только консольный компилятор.

Если бы мы увидели, что что-то хоть раз не собралось - мы бы явно по-другому относились к этой проблеме.

У @spectatorBH эта проблема насколько я понял возникает если он скачивает zip-архив. Только в этом случае.

**Comment by SunSerega** [comment]
Я с котовым поговорил на эту тему, он говорит что у него самого проблемы с неправильными переносами строк прекратились примерно когда он перешёл на Github Desktop.
Я сам использую TortoiseGit, а он напрямую выполняет консольные .exe гита (и показывает их вызов и вывод).

Давайте смотреть на тест `TestSuite\formatter_tests\input\arrays4.pas`, это первый из тех что не проходят сейчас.

В папке `input`:
![image](https://user-images.githubusercontent.com/27270190/93015404-e2283300-f5c1-11ea-87f6-13f7cb227782.png)

В папке `output`:
![image](https://user-images.githubusercontent.com/27270190/93015420-fbc97a80-f5c1-11ea-9492-858b8ad0ca72.png)

Если в конце строки стрелка вниз - это перенос строки состоящий только из `#10`. А если значок как на клавише `Enter` - значит перенос строки состоит из `#13#10`.

То есть в папке `input` все переносы строк это `#10`. А в папке `output` - месиво из `#13#10` и `#10`.

---

Что ещё интересно - в папке `should` этого файла нет. Там много чего нет.
С чем вообще сравнивает результат из `output`? С исходным файлом? По моему это бред...

**Comment by miks1965** [comment]
Я пользуюсь TortouseGit.
У меня в TestSuite\formatter_tests\input\arrays4.pas везде стоят #13#10

**Comment by SunSerega** [comment]
Хорошо, тогда откройте его настройки через ПКМ в папке своей репы и скиньте содержимое файла под этой кнопкой:
![image](https://user-images.githubusercontent.com/27270190/93023260-701e1100-f5f6-11ea-96fd-4f5623ca5b3c.png)

У меня так:
```
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=false
core.fscache=true
core.symlinks=false
core.editor="C:\\Program Files\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
credential.helper=manager
pull.rebase=false
user.name=SunSerega
user.email=latchenko3@yandex.ru
credential.helper=manager
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=git@github.com:pascalabcnet/pascalabcnet.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```

**Comment by spectatorBH** [comment]
@miks1965 Нет, это НЕ проблема гитхаба или zip! В вашей репе на гитхабе сейчас все текстовые файлы хранятся в LF-формате (так уж она была вами создана). Я использую скачивание через zip только для чистоты эксперимента -- чтобы на содержимое гарантированно не влияли никакие промежуточные утилиты (гит-клиенты), т.к. выяснилось, что у таких утилит есть возможность на лету менять формат окончаний строк в текстовых файлах. Причем дефолты у разных утилит и на разных системах могут быть разные! Мой GitKraken сейчас ничего не перекодирует по умолчанию, но в нем также есть эта настройка и я пока не знаю, работает ли она в обе стороны или только в одну, поэтому пока её не использую.

@SunSerega Собственно, у вас на скриншоте она есть, даже из 2 пунктов: AutoCrLf (откл.) и SafeCrLf. Вторая, возможно, отвечает за обратную перекодировку при Push, если активирована первая (для Pull, Checkout и т.п.).

**Comment by spectatorBH** [comment]
> То есть в папке input все переносы строк это #10. А в папке output - месиво из #13#10 и #10.

Я не понимаю, почему обсуждение в этой ветке съехало в эту сторону -- это совсем другая проблема, описанная отдельно в #196! Я уже второй раз об этом напоминаю. Данная проблема именно об ошибке **SyntaxTreeNotEquals**, которая возникает со **свежим** (т.е. если его вручную скопировать) PABCSystem.pas в папке TestSuite\formatter_tests\input и **НЕ зависит от формата LF<->CR/LF**. 

> Причем, без разницы в каком формате будет этот новый PABCSystem.pas -- 475 209 bytes (LF) или 488 671 (CR/LF) от 09.09.2020 -- первая ошибка в логе будет та же (SyntaxTreeNotEquals), остальные -- да, уже зависят от формата лайн-брейков.

Кроме того, она не ограничивается только этим единственным файлом -- с другими файлами со сложным кодом и структурой (если их поместить в \input) она проявляется точно также: напр., **OpenCL.pas** (1), **OpenCLABCBase.pas** (2) и **OpenGL.pas** (1). 

_(1) -- ошибка с PascalABCCompiler.SyntaxTree_.**dot**__question_node_
_(2) -- ошибка с PascalABCCompiler.SyntaxTree_.**double**__question_node_

**Comment by ibond84** [comment]
Я закрываю issue и переоткрываю новый про баг с новым PABCSystem. Просьба там про проблемы git-а с символом новой строки не писать

**Comment by spectatorBH** [comment]
> Просьба там про проблемы git-а с символом новой строки не писать

@ibond84 Согласен, в той новой issue упоминать про этот момент совсем ни к чему -- только я не понимаю, почему вы продолжаете считать это проблемой git-а: git-у все равно в каком формате хранить строки, в нашем случае на сервере все хранится в LF-формате и скачивается с него также (что zip-ом через веб-интерфейс, что git-клиентами через https или SSH).

Но есть нюанс в том, что проблемы, упомянутые в #195 и #196, **не заметны** для тех, у кого git-клиенты (точнее, их Windows-версии) настроены на *автоматическую локальную перекодировку уже загруженных с гитхаба текстовых файлов* (видимо, они автоматом также выполняют и обратную перекодировку перед Push-ем) -- такая **незаметная ситуация** сейчас у вас, @ibond84, и у @miks1965. У меня же и, по крайней мере, у @SunSerega сейчас ничего автоматом не перекодируется на лету, так же как и в стандартных преднастроенных образах хост-раннеров (VM) Windows Server 2016 и Windows Server 2019 самого гитхаба, поэтому мы с этим столкнулись, а вы у себя -- нет. 

Но это не значит, что проблемы не существует или она на стороне гитхаба или гит-клиентов: сборка и тестирование не должны никак зависеть от формата окончаний строк, тем более не должно быть никаких проблем **при отсутствии перекодирования** файлов из офиц. репозитория.
