### ISSUE TITLE
Лишняя пустая строка после uses при форматировании некоторых LF-файлов в IDE

### ISSUE THREAD

**Issue by spectatorBH** [pascalabcnet/pascalabcnetide#195]
Если в IDE открыть файл `TestSuite\formatter_tests\input\arrays4.pas` в его **LF-варианте** и запустить форматирование более 1 раза, то добавится лишняя (2-ая) пустая строка после `uses arrays4u;`. При этом, если удалить эту лишнюю строчку в редакторе, после переформатирования она появится снова. 

Проблема не проявляется, если файл изначально был в CR/LF-формате (или сохранен в редакторе и переоткрыт, что автоматически конвертирует его окончания строк).

**Comment by ibond84** [comment]
При загрузке файла юниксовские переносы строк теперь автоматически заменяются на CR/LF.
