### ISSUE TITLE
Смешанные окончания строк (CR/LF и LF) в некоторых LF-файлах после их форматирования в TestRunner

### ISSUE THREAD

**Issue by spectatorBH** [pascalabcnet/pascalabcnetide#196]
В тестах форматирования TestRunner при обработке input-файлов в **LF-варианте** результаты сохраняются в \output уже в CR/LF-формате, но при этом в некоторых файлах (сейчас их 20 шт. – см. в [логе](https://github.com/pascalabcnet/pascalabcnetide/files/5184889/log.txt) все файлы с ошибками в строках №3 или №4) одна из строк после форматирования остается с LF-окончанием, т.е. получается мешанина из окончаний.

**Comment by ibond84** [comment]
Ну, ничего не понятно.  В Testing.cs  \r\n при сравнении заменяются  на \n Какая там мешанина?

**Comment by ibond84** [comment]
И да, в чем суть ошибки вообще? TestRunner ругается?

**Comment by spectatorBH** [comment]
Если исходные файлы в `\input` имеют LF-окончания всех строк (а именно в таком виде они хранятся сейчас в вашем официальном репозитории) и при этом они НЕ БЫЛИ автоматически перекодированы в стандарт Windows (CR/LF) *локальным гитхаб-клиентом* при их загрузке/обновлении из удаленного репозитория (что является сугубо опциональной функцией таких клиентов, не всегда вкл. по умолчанию), то `TestRunner 6` завершается с ошибкой, т.к. при форматировании **некоторых** из этих файлов форматтер создает их копии в `\output` со смешанными окончаниями: одна из первых строк сразу между `uses` и `begin` остается с LF, а все остальные -- CR/LF. В результате тест не проходит -- лог ниже:

```
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\arrays4.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\bigint.pas, line 4
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\delegates5.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\Demo1.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\diapasons2.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\enum2.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\File48.pas, line 4
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\flagsattr1.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\incdec2.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\LibForHaskell.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\MathForKumir.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\PT4.pas, line 27
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\PT4DemoTest.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\RBDMUtilsDemo.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\records3u.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\set2.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\set5u.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\String9.pas, line 4
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\typedconst2.pas, line 3
Invalid formatting of File D:\TEMP\GitHub-projects\pascalabcnet-WIP\TestSuite\formatter_tests\output\typedconst2u.pas, line 3
```

Первый раз я столкнулся с этой проблемой, отлаживая удаленную сборку средствами GitHub Actions -- в их преднастроенных образах виртуальных машин (Windows Server 2016/2019) официальный консольный гит-клиент как раз НЕ ПЕРЕКОДИРУЕТ окончания текстовых строк в Windows-формат при клонировании репозитория для сборки (и это там не настраивается), из-за чего тесты все время падали в этом месте. Чтобы разобраться что к чему, я скопировал свежий срез репозитория к себе локально напрямую -- через их веб-интерфейс как zip-файл (т.е. "как есть", без лишней обработки моим гит-клиентом) и прогнал тесты в отдельной чистой папке -- тогда и прояснились все детали.

P.S. Кстати, эта проблема с появлением смешанных окончаний строк после форматирования проявляет себя и в IDE (проверял с тем же набором проблемных файлов), но чуть иначе (см. #195) хотя это уже не критично: просто наткнулся, экспериментируя с ними локально.

**Comment by ibond84** [comment]
>и при этом они НЕ БЫЛИ автоматически перекодированы в стандарт Windows (CR/LF) локальным гитхаб-клиентом при их з

Эту опцию надо включать обязательно. Тогда все будет работать
