### ISSUE TITLE
SyntaxTreeNotEquals в TestRunner со свежим PABCSystem.pas в TestSuite\formatter_tests\input\

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnetide#198]
TestRunner выдает следующую ошибку, если обновить файл PABCSystem.pas (свежая версия взята из сборки 3.7.1-2677) в TestSuite\formatter_tests\input:

```
***ERROR: check TestSuite/formatter_tests/output/log.txt:
SyntaxTreeNotEquals PascalABCCompiler.SyntaxTree.dot_question_node <...>\TestSuite\formatter_tests\input\PABCSystem.pas
```

**Comment by spectatorBH** [comment]
Поскольку предыдущий issue был закрыт из-за комментариев не по теме, повторяю своё уточнение здесь:

Проблема не ограничивается только этим единственным файлом -- с некоторыми другими файлами со сложным кодом и структурой (если их поместить в \input) она проявляется аналогично: напр., свежие OpenCL.pas (1), OpenCLABCBase.pas (2) и OpenGL.pas (1).

_(1) -- ошибка с PascalABCCompiler.SyntaxTree._**dot**__question_node_
_(2) -- ошибка с PascalABCCompiler.SyntaxTree._**double**__question_node_

**Comment by miks1965** [comment]
У меня TestRunner не выдаёт никакой ошибки на PABCSystem.pas

**Comment by spectatorBH** [comment]
Странно... У меня и у @SunSerega ошибка есть, у вас -- нет. А что у вас с другими упомянутыми выше файлами? 

Надо, чтобы кто-то еще протестировал этот момент. @AIexandrKotov, как у вас такие тесты проходят?

**Comment by miks1965** [comment]
Я не вижу тут никаких упомянутых файлов

**Comment by miks1965** [comment]
![изображение](https://user-images.githubusercontent.com/10325391/93228288-fd3fa200-f77d-11ea-9200-4b4511fa4755.png)

**Comment by miks1965** [comment]
То есть, проходят все и проходили всегда. Там лежит файл PABCSystem.pas в частности

Никаких #10 на концах строк у меня нет. Не забываем, что эти файлы появляются вначале на компьютерах разработчиков, а потом уж чудодейственно перекодируются GitHubом

**Comment by SunSerega** [comment]
> Я не вижу тут никаких упомянутых файлов

Вы точно прочитали [вот это](https://github.com/pascalabcnet/pascalabcnetide/issues/198#issuecomment-692276320)?

**Comment by miks1965** [comment]
Да, увидел. На этих файлах падает

**Comment by SunSerega** [comment]
И `PABCSystem.pas` тоже надо **новый** перекопировать в ту папку, чтоб он упал. Старый, который сейчас сохранён в вашей репе - ни у кого не падает.
