### ISSUE TITLE
Intellisense - Aggregate (y,x)

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnetide#200]
```
begin
  Arr(1,2,3).Aggregate(1.0, (y, x) → (y * (x mod 10)));
end.
```
При наведении на x и y типы показываются наоборот

**Comment by SunSerega** [comment]
@ibond84 там ещё 1 соседняя issue, раз уже переносите:
https://github.com/pascalabcnet/pascalabcnet/issues/2357

**Comment by ibond84** [comment]
Исправлено в семантическом интеллисенсе
