### ISSUE TITLE
Неверный тип при наведении.

### ISSUE THREAD

**Issue by SIR20** [pascalabcnet/pascalabcnetide#206]
```
begin
  var a := Arr('11', '22', '33').Select(i -> i.ToInteger());
end.
```
![image](https://user-images.githubusercontent.com/50875831/113717418-46444d00-96f4-11eb-8ba5-ec71f111cb69.png)
Должно быть **of integer**

**Comment by ibond84** [comment]
Исправлено в семантическом интеллисенсе
