### ISSUE TITLE
Подключение манифеста

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnetide#208]
После компиляции любого кода со строкой `{$mainresource ‘Путь до манифеста’}` среда выдаёт в окно вывода:
"Произошла непредвиденная ошибка. Вероятно, на диске отсутствует .exe-файл. Повторите запуск".  После этого IDE клинит. Значёк остановки программы остаётся доступным, но при его нажатии ничего не происходит. Помогает только перезапуск.
Однако в папке можно найти нормально скомпилированный .exe, который даже запускается.
К стати манифест на запрос прав админа в расширении .res
Проблема не существенная, но каждый раз запускаться из папки и перезапускать IDE как то не очень хочется

**Comment by SunSerega** [comment]
Дайте пример такого .res файла, как вы говорите.

**Comment by samuraiGH** [comment]
@SunSerega на форуме кидал файл в раздел ошибок IDE, но меня зачем то отправили создавать тему здесь. кинул бы ссылку на форум, но он походу упал

**Comment by miks1965** [comment]
Нет, на форуме всё это потеряется

**Comment by SunSerega** [comment]
Ну так в любом случае, надо этот файл. И стоит и ссылку на ваше сообщение с форума сразу, чисто чтоб если потом разбираться - было видно откуда пришло.

**Comment by samuraiGH** [comment]
@miks1965 @SunSerega 
[installer_resource.zip](https://github.com/pascalabcnet/pascalabcnetide/files/6795055/installer_resource.zip)
пришлось заархивировать, так как гх .res видимо не принимает. 
Ссылку на пост кину, когда оживёт форум, но это по сути дубликат

**Comment by ibond84** [comment]
Здесь ошибка только в лагании среды. Файл ресурсов неправильный.

**Comment by ibond84** [comment]
Исправлено

**Comment by samuraiGH** [comment]
@ibond84  Теперь среда действительно не зависает. Однако с тем, что файл ресурсов неправильный - не согласен. Компилятор как генерирует рабочую программу, так и генерирует. Никаких ошибок в программе с таким манифестом так же не обнаруживал. Ругается только среда со своим:
>Произошла непредвиденная ошибка. Вероятно, на диске отсутствует .exe-файл. Повторите запуск

Не спорю, что в манифесте разбираюсь не особо, так что взял его от сюда: https://bad-good.ru/2014/august/point-manifest.html
