### ISSUE TITLE
PascalABC.net breaks the encoding of existing pascal files

### ISSUE THREAD

**Issue by Sturwandan** [pascalabcnet/pascalabcnetide#209]
I have multiple *.pas files which are plain ASCII with nothing fancy in them and simple ``\n`` line terminators.
However, when such a file is opened with PascalABC.net IDE, a UTF-8 BOM is added in the beginning of file and line terminators are converted to ``\r\n``. This behavior is inappropriate, because BOM in UTF-8 is never needed at all, except to overcome problems in buggy software, and even less useful when there are absolutely none non-ASCII characters.

However, many implementations of Pascal won't compile such a file, because of the garbage at the beginning of a file, including very popular, but slightly outdated Turbo Pascal, which means you would need to open the file with a smart text editor and re-save it or use command line conversion tools.

Line terminators of ``\r\n`` format are a legacy of ancient teletypes which needed two commands to move the mechanical printer head to the beginning of the new line first, and only then to scroll the paper upward.
Microsoft has forced this ancient convention upon the personal computers with the DOS system, however times of DOS are long gone and all modern text editors and text processing tools, but MS Notepad support ``\n`` terminating the lines. 

Incorrect terminators are less problematic then BOM, but it would be nice if, by default, the ABC IDE preserved the BOM and line terminator conventions of the source file: if there is BOM, don't strip it, if there is no BOM, don't add it, if there are`` \n`` , don't add ``\r``, if there are ``\r``, don't strip them.

Though this should be changeable in settings, with separate options for Encoding, BOM and Line Terminators:
For BOM: add it upon saving, remove it upon saving, preserve it as it is.
For Terminators: convert to `\n`, convert to `\r\n`, preserve.
For Encoding: convert to UTF-8, preserve.

Upon saving a file, PascalABC.net should always make sure that the last line is terminated with the correct line terminating sequence. Currently, the user has to add a terminator after ``End.`` statement manually, otherwise the file is saved incorrectly.

Unterminated lines at the ends of text files might cause problems with various programs, while there is no downside from having a correct line terminator sequence (``\n`` or ``\r\n``, same as elsewhere in the file) after the last printable character of the file.

**Comment by miks1965** [comment]
Don't use old Pascals or be ready to get problems.

> because BOM in UTF-8 is never needed at all

It's very strange. The BOM format is the de-facto standard of saving files. For instance, Visual Studio saves files in this format.

> Microsoft has forced this ancient convention upon the personal computers

It's very strange too. This agreement is also standard for windows and you translate here only your own opinion.
Visual studio saves all files with \r\n delimiters

> otherwise the file is saved incorrectly

You have not provided any proof of this statement

**Comment by Sturwandan** [comment]
@miks1965 If Visual Studio is buggy it doesn't mean that you have to replicate all its bugs.

``\r\n`` delimiters are outdated, since most windows programs can deal with ``\n`` delimiters with ease. So if file was imported into PascalABC it should not downgrade the delimiters upon saving, without user even knowing about it. It should be an option in settings. ``\n`` delimiter is shorter, so it's better.

> The BOM format is the de-facto standard of saving files.

The main reason why UTF-8 is so great is its full compatibility with ASCII, however BOM breaks this compatibility, which means that ASCII-only file stops being ASCII-only without a reason. BOM serves absolutely no purpose whatsoever in UTF-8, it's only necessary for UTF-16 and UTF-32 formats, which can be saved in Little-Endian or Big-Endian. UTF-8 is always the same, it doesn't matter on which processor architecture it is defined, the most significant byte comes first.

Since the main and only purpose of the Byte Order Mark is to mark the byte order, and UTF-8 always has the same byte order, its use in UTF-8 is erroneous. Only reason why it was added to UTF-8 by Notepad.exe and Visual Studio was lack of thinking straight.

> You have not provided any proof of this statement

By incorrect, I mean that if you check the saved file with hexdump, than the last line is going to be missing the line terminator. Line terminators are mandatory for many text processing tools, even if they are aren't for most graphical text editors.

**Comment by Sturwandan** [comment]
An example, when BOM causes problems https://stackoverflow.com/questions/44098326/ef-bb-bf-at-the-beginning-of-json-files-created-in-visual-studio
I would rather do something with Visual Studio settings, if I were you, to make it turn auto-detection of encoding wrong and always assume that the file is UTF-8 without a BOM. It's better to fix problem in your code rather then mimicking buggy default behavior of other programs such as Visual Studio.
