### ISSUE TITLE
PascalABC.net IDE breaks ASCII-only Pascal files by inserting bogus byte-order-marks.

### ISSUE THREAD

**Issue by Sturwandan** [pascalabcnet/pascalabcnetide#210]
When you open a correct pascal file in PascalABC.net IDE and then save it, bogus bytes are added at the beginning, which makes the resulting file incompatible with many text processing tools and other pascal implementations. My suggestion is to stop inserting those bytes, or at least make it optional. The rest of the report explains why.

The Byte-Order-Mark is a pseudo-character, which is used by some applications to detect the byte order of UTF-16 and UTF-32 encodings. The confusion here strives from the fact that USC-2 (predecessor of UTF-16) and UTF-32 are simply arrays of integers (unsigned 16 bit and 32 bit correspondingly), holding Unicode character codes. And this means, that on Little-Endian machines such as Intel x86, character U+044B "ы" (Cyrillic letter "Yery") is represented as bytes 4B 04 and on Big-Endian systems it would be written 04 4B, while character U+4B04 "䬄" (Chinese character "Xù"), would be written as 04 4B on LE machine and 4B 04 on BE machine. 

So a character U+FEFF (former zero-width space) was chosen to be put in front of USC-2, UTF-16 or UTF-32 data to avoid confusion, because its byte-swapped cousin U+FFFE  ￾ is not a character, so it cannot be found in valid Unicode file.

Unlike plain formats described above, UTF-8 uses a variable-length encoding, with the first byte always holding  the most significant bits of the Unicode character code, and then, depending on its other bits, the byte-length of complete character is determined. For example, Unicode characters below 128 are encoded in one byte of format 0xxx xxxx (binary), which means that UTF-8 is fully compatible with ASCII, while values of 128 and above, up to 2047 are encoded as 110x xxxx 10xx xxxx representation, where the first byte is starting with 110, and two 1's mean that complete character is two bytes long, and the remaining bytes always start with 10 and hold six bits of actual character values, which allows to represent character up to U+07FF in 2-byte UTF-8 sequences.
Three byte sequences have similar structure: 1110 xxxx 10xx xxxx 10xx xxxx and so on. The number of 1's followed by 0s tells us how long the code is. x-bits represent actual bits of the character code.

As you can see, UTF-8 is a well-defined format unlike UTF-16 and more than that, the first byte of a sequence can be easily told apart from latter bytes and well-formed UTF-8 is easy to distinguish from malformed one fully automatically, making any special marks, indicating byte order absolutely unnecessary.

Since the main feature of UTF-8, compared to UTF-16, is full compatibility with ASCII, this means that BOM is not only unnecessary, but also harmful, since UTF-8 with BOM is no longer compatible with ASCII.

Even worse than that, some programs started to depend on presence of those bogus bytes, but those programs are also erroneous, because it's easy to detect UTF-8 fully automatically without any special marks. It is enough to assume UTF-8 by default and fall back to different encoding, if decoding the file as UTF-8 fails.

Nevertheless, some text editors erroneously insert BOM into UTF-8, where it makes no sense, and that, unfortunately, includes PascalABC.net IDE. I have tried to create [a bug report in there](https://github.com/pascalabcnet/pascalabcnetide/issues/209), but it was closed without the issue being fixed. I guess that happened because I have mixed several different problem into one issue, so I guess it's better to make separate issues for each problem.

**Comment by miks1965** [comment]
We closed this issue earlier with the answer that we consider the behaviour of our text editor absolutely correct - as in Visual Studio.

Please don't spam here via reopening old issues

**Comment by Sturwandan** [comment]
@miks1965 but PascalABC.net IDE is not Visual Studio.
Why do you think, that it must replicate and propagate all its bugs?
Especially if fixing this particular issue should not cause any compatibility problems at all?

Visual Studio is not only programmer's text editor and other editors do not have this problem. They usually allow to change it in setting or just treat BOM as ordinary character. But if the wrong behavior is hardcoded, as in this case, then what am I supposed to do? Should I run a script every time after I save a file in PascalABC IDE to clean it up and strip bogus BOM or something?

I did not get a satisfying answer why do you simply ignore all my arguments from above. Did you read them at all? Byte-Order-Mark, as it follows from its name is meant to indicate **the order of bytes**. In UTF-8 the order is always same, there is *nothing* to indicate.
