### ISSUE TITLE
Принудительно чёрный фон в выводе компилятора под Linux

### ISSUE THREAD

**Issue by sibskull** [pascalabcnet/pascalabcnetide#211]
![pabcnetc](https://user-images.githubusercontent.com/577967/128536058-fd4e1e9c-6469-429d-8ea4-8afd7692509d.png)

Принято в консольных утилитах не менять фон терминала.

**Comment by miks1965** [comment]
Можно сделать Pull Request - проект открыт

**Comment by sibskull** [comment]
Посмотрю. Но я C# практически не знаю.

**Comment by miks1965** [comment]
Насколько я понимаю, это в устаревшем pabcnetc - в консольном компиляторе pabcnetcclear нет интерактивного режима и цвета вообще. Он как раз используется в олимпиадах и как раз под Linux
