### ISSUE TITLE
В подсказке по наведению неверный тип для foreach от ListBox.SelectedIndexCollection 

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnetide#219]
```
{$reference system.windows.forms.dll}
##
var coll: system.windows.forms.ListBox.SelectedIndexCollection;
foreach var a in coll do
  a.IsEven.print;
```

> ![image](https://user-images.githubusercontent.com/87191377/136251705-1277e4ff-4095-4809-bd76-e3063e536642.png)

ну и на выходе естественно 
> Program1.pas(5) : IsEven не объявлен в типе object

**Comment by ibond84** [comment]
Исправлено в семантическом интеллисенсе
