### ISSUE TITLE
Ошибка при подключении манифеста с UAC-запросом 

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnetide#221]
Считаю #208 не законченной. 
Перепробовав n-ное количество манифестов убедился, что ошибка

> Произошла непредвиденная ошибка. Вероятно, на диске отсутствует .exe-файл. Повторите запуск

 возникает с любым из них. Компилятор опять же реагирует нормально на любой из манифестов.
 http://forum.mmcs.sfedu.ru/t/oshibki-ide-pascalabc-net/2532/131

**Comment by ibond84** [comment]
Ничего непонятно. Что значит " Компилятор опять же реагирует нормально на любой из манифестов."?

**Comment by ibond84** [comment]
И что за манифест с UAC-запросом? Нужны конкретные примеры. И такие, которые работают в VS, но не работают в PABC.NET

**Comment by samuraiGH** [comment]
Тогда ещё раз..

1. Берём манифест. Например такой:
<details>

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
<assemblyIdentity version="1.0.0.0" processorArchitecture="*" name="1" type="win32"/>
	<trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
		<security>
			<requestedPrivileges>
				<requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
			</requestedPrivileges>
		</security>
	</trustInfo>
</assembly>
```

</details>
На практике можно взять какой угодно. Хоть бы и  такой:
<details>

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
<assemblyIdentity
    version="1.0.0.0"
    processorArchitecture="*"
    name="Project1"
    type="win32"
/>
	<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
		<security>
			<requestedPrivileges>
				<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
			</requestedPrivileges>
		</security>
	</trustInfo>
    <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
      <application>
            <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/> 
            <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
            <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
            <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
            <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
      </application>
    </compatibility>
</assembly>
```

</details>

2. Собираем всё это с помощью [Resource Hacker](http://www.angusj.com/resourcehacker)

3. Пытаемся **запустить** такую программу

```
{$mainresource resource.res}

begin
  print('good');
end.
```

4. Получаем
> Произошла непредвиденная ошибка. Вероятно, на диске отсутствует .exe-файл. Повторите запуск
5. Пытаемся **скомпилировать** то же самое
6. Получаем нормальный .exe файл без каких либо последствий

Такое поведение характерно для любых манифестов с UAC-запросом.
Пример UAC-запроса в других программах:
![image](https://user-images.githubusercontent.com/87191377/136698602-6763ef71-18a4-4a2c-99d3-682dd4a607f1.png)
Ну то есть речь о правах администратора, о чём и говорилось в прошлой issue

**Comment by ibond84** [comment]
У меня все работает. Возможно исправилось исправлением #2558

**Comment by samuraiGH** [comment]
@ibond84 `3.8.2.3037` ошибка та же самая 

> Произошла непредвиденная ошибка. Вероятно, на диске отсутствует .exe-файл. Повторите запуск

**Comment by ibond84** [comment]
Попробуйте отключить антивирусы. У меня не воспроизводится.

**Comment by samuraiGH** [comment]
@ibond84 
> Попробуйте отключить антивирусы

Вырезан даже Защитник Виндовс
