### ISSUE TITLE
Неверная подсказка для array.min с лямбдой 

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnetide#223]
```
##
var a: array of integer;
a.Min(p -> p[0]);
```
![image](https://user-images.githubusercontent.com/87191377/138155466-069d76dc-7370-42ad-adca-60f848ac2fca.png)
 
Ну и соотвественно выпадает ошибка

> Нет индексного свойства по умолчанию для типа integer

С array.max то же самое

**Comment by ibond84** [comment]
Исправлено в семантическом интеллисенсе
