### ISSUE TITLE
Неправильное определение типов в подсказках IDE

### ISSUE THREAD

**Issue by Anonymous87549236** [pascalabcnet/pascalabcnetide#224]
![image](https://user-images.githubusercontent.com/70477515/138285105-87a607ad-ef1c-4d3b-94aa-db4566386c13.png)
![image](https://user-images.githubusercontent.com/70477515/138285150-b6b80d24-446b-42db-857a-dd16e38a40bf.png)
![image](https://user-images.githubusercontent.com/70477515/138285172-35f2379c-3a7e-476f-99ba-2ea34e8a9b3b.png)

**Comment by SunSerega** [comment]
Выглядит как куча отдельных issue, при этом ни в 1 из случаев не представлен полный код, который можно вставить в IDE и воспроизвести неправильное поведение.
А без чётко определённой ситуации с неправильным поведением - дебажить нечего.

**Comment by Anonymous87549236** [comment]
Ясно. Подсказки не обновляются, если сначала написали код с ошибкой, а потом — изменили тип.
