### ISSUE TITLE
Исключение без try выводится асинхронно

### ISSUE THREAD

**Issue by Anonymous87549236** [pascalabcnet/pascalabcnetide#225]
![image](https://user-images.githubusercontent.com/70477515/138285431-ecb4fb7d-3b3b-4762-83b1-64d4a06f3732.png)

**Comment by Anonymous87549236** [comment]
Если интересно исключение, то вот:
```
/// Сравнивает словари a и b по элементам.
function AreDictEqualSpecific(a, b: Dictionary<char, integer>): boolean;
begin
  Result := a.Count = b.Count;
  if Result then
  begin
    var ae := a.GetEnumerator;
    var be := b.GetEnumerator;
    loop a.Count do
    begin
      ae.MoveNext;
      be.MoveNext;
      if (ae.Current <> be.Current) then
        Result := false;
    end;
  end;
end;

/// Сравнивает словари a и b по элементам. Попытка обобщения AreDictEqualSpecific. Непреднамеренно вызывает исключение.
function AreDictEqual<T1, T2>(a, b: Dictionary<T1, T2>): boolean;
begin
  Result := a.Count = b.Count;
  if Result then
  begin
    var ae := a.GetEnumerator;
    var be := b.GetEnumerator;
    loop a.Count do
    begin
      ae.MoveNext;
      be.MoveNext;
      if (ae.Current <> be.Current) then
        Result := false;
    end;
  end;
end;

begin
  var a := KV('a', 1);
  var b := Dict(a);
  var c := Dict(a);
  Writeln(b = c); //Почему False?
  Writeln(AreDictEqualSpecific(b, c)); //True
  //Write(AreDictEqual(b, c)); // То самое исключение
end.
```

**Comment by SunSerega** [comment]
0. Зачем вы комментируете то что даёт ошибку, нужную для воспроизведения?
1. Текст не разрывает, скорее - текст ошибки приходит асинхронно, относительно текста вывода. Если словить через `try-on` и вывести ошибку - будет ок.
2. `InvalidProgramException` значит что компилятор сгенерировал не_читаемый .exe файл - это отдельная issue. Но надо найти минимальный код, а не всё вот это.
3. > Почему False?
   
   Ваша попытка сравнить, перечислив все значения - эффективнее реализуется 1 вызовом `.SequenceEqual`, а ещё не работает. Потому что `Dictionary` это в первую очередь множество (у которого у кажому `TKey` приписывается ещё 1 значение `TValue`). А у множеств порядок, в котором идут элементы, не определён.
   Нормальный алгоритм, выполняющий полное сравнение, будет затратный, поэтому по-умолчанию не реализован. А раз словарь это класс (т.е. ссылочный тип) - сравниваются ссылки (адреса в памяти), которые у 2 отдельных объектов разные.

**Comment by SunSerega** [comment]
Для `InvalidProgramException` сам нашёл минимальный код:
https://github.com/pascalabcnet/pascalabcnet/issues/2548
