### ISSUE TITLE
Неверная подсказка для процедурных переменных от static методов

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnetide#227]
```
type
  a = class
    static function fun(x: integer): integer;
    begin end;
  end;

begin
  var p:= a.fun;
end.
```
![image](https://user-images.githubusercontent.com/87191377/139884243-96c7f6f5-b276-428d-9677-49ae4cfda76e.png)

если сменить функцию на процедуру, то подсказки вообще не будет

**Comment by ibond84** [comment]
Исправлено в семантическом интеллисенсе
