### ISSUE TITLE
Нет подсказок по точке для устаревших типов

### ISSUE THREAD

**Issue by Anonymous87549236** [pascalabcnet/pascalabcnetide#248]
Например, короткие строки и статические массивы, конечно, "для совместимости со старыми Паскалями", но у них есть `GetType`.
```
##
var a: string[5];
var b: array [1..3] of integer;
```
![image](https://user-images.githubusercontent.com/70477515/176879488-f5e383c5-56e6-4fcb-9a7d-7111c2d150cd.png)
![image](https://user-images.githubusercontent.com/70477515/176879507-ed846e80-07cd-4c24-b9a3-093700cfbacc.png)

**Comment by miks1965** [comment]
И не будет - они - "волшебные". Не пользуйтесь ими )
