### ISSUE TITLE
Перекомпилировать всё перестала работать между 1.01.22 и 09.01.22. Видимо после пуллреквеста SunSerega

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnetide#254]
![изображение](https://user-images.githubusercontent.com/10325391/197357678-b6f8cac0-4596-4c56-bc3b-aadc9d4b379c.png)

**Comment by SunSerega** [comment]
После какого из них?

**Comment by miks1965** [comment]
Я не знаю - я просто посмотрел точки 1 января 2022 г - там всё работало - потом 9 января 2022 г - там уже нет. Где-то между ними было много ваших коммитов.

Я подозреваю, это связано с uses in и изменением алгоритма компиляции.

Это серьёзный баг - как мы его не заметили до сих пор - ума не приложу.

Собственно, раньше стандартные модули не участвовали в перекомпиляции

**Comment by SunSerega** [comment]
Странно ещё потому что перекомпиляция (компиляция с `/rebuild`) происходит несколько раз при сборке билда, со всеми модулями. Чем отличается та перекомпиляция что у вас? И как именно вы выспроизводите?

**Comment by miks1965** [comment]
Установите себе версию с сайта. Сут там такая - pcu находятся в Lib, а исходники - в LibSource. С некоторого момента Перекомпилировать всё стал искать именно исходники в папке Lib - и когда не находит их - возникает ошибка

Для проверки можно самому создать папку libSource и перенести в нее все исходники

**Comment by SunSerega** [comment]
Подождите, то есть вы хотите чтобы кнопка перекомпиляции брала модули из `LibSource`??? Они же туда ставятся только для анализатора кода.
А стандартные модули компилируется только при создании билда - когда они в папке `bin\Lib` данной репы.

Ошибки, конечно, не должно быть, но по моему стандартные модули должны всё равно загружаться из .pcu, даже если нажато перекомпилировать всё.
Если надо стандартные модули перекомпилировать - надо их копировать в папку с программой. Чтобы была как бы рабочая, изменяемая копия, в отличии от запечатанных модулей что идут с установщиком.

**Comment by miks1965** [comment]
Нет, перекомпиляция вообще должна не затрагивать системные модули
