### ISSUE TITLE
Для типов, объявленных в разделе реализации модуля не работает интеллисенс

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnetide#255]
```pas
unit u1;
interface 

implementation

type 
  c1 = class
    f1: string;
  end;

  procedure pr1;
  begin
    var i1:= new c1;
    i1.  // подсказка не появляется
  end;

end.
```

**Comment by SunSerega** [comment]
Очень странно что я раньше ни разу такого не заметил, но теперь воспроизводится на одном из последних коммитов. На сколько у вас новая версия?

**Comment by samuraiGH** [comment]
@SunSerega Судя по всему, уже было на `3.8.3.3147` По крайней мере, это самый "новый" из сохранившихся установщиков. Перед репортом как раз обновился просто
