### ISSUE TITLE
IDE может создать два файла "Program1", если перед этим был открыт стандартный модуль с помощью intellisense

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnetide#258]
1. Открываем IDE
2. Пишем например
`## uses plotwpf;`
3. ПКМ по `plotwpf` -> Перейти к определению
4. Ctrl+N
![image](https://user-images.githubusercontent.com/87191377/200166000-1bbdebd0-e39f-467f-b451-df8bd9444c38.png)

С пользовательскими модулями такого поведения не поймал. При открытии  стандартного модуля через `PascalABC.NET\LibSource` тоже не поймал

UPD: новый файл нужно создавать находясь в модуле, иначе не проявляется

**Comment by miks1965** [comment]
Ну это правильно. Новый файл всегда создается в каталоге открытого файла. Эти два Program1 находятся в разных каталогах

**Comment by samuraiGH** [comment]
а, вот как. я думал, что файлы не имеющие "физической" формы живут в pabcwork, пока их не сохранишь

**Comment by miks1965** [comment]
Ну, они то не имеют, но каждый готов сохраниться в свой каталог
