### ISSUE TITLE
Add Clear Recent Files to IDE

### ISSUE THREAD

**Issue by 2cls0f** [pascalabcnet/pascalabcnetide#262]
File -> Recent Files -> Clear Recent Files

**Comment by miks1965** [comment]
I don't see such menu item in production IDEs (Visual Studio):
![изображение](https://user-images.githubusercontent.com/10325391/213862160-0eaa3ee6-0670-47d4-aef4-6c1aaaeab99c.png)
Sorry

**Comment by 2cls0f** [comment]
Recent Files doesn't have, but Recent Projects and Solutions right next to Recent Files has.
