### ISSUE TITLE
Intellisense не умеет выбирать между перегрузками с одинаковыми аргументами, одна из которых параметризирована

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnetide#263]
```pas
function f1: object;
begin end;

function f1<T>: T;
begin end;

begin
  var t:= f1&<integer>;
end.
```
Выбирает первую попавшуюся перегрузку. Если поменять их местами, то будет уже integer
![image](https://user-images.githubusercontent.com/87191377/219113927-ab95dfd2-9585-4397-a74a-9feed651bab2.png)

**Comment by ibond84** [comment]
Включите семантический интеллисенс.
