### ISSUE TITLE
Could you make PascalABC.NET to follow system's scaling setting?

### ISSUE THREAD

**Issue by ghost** [pascalabcnet/pascalabcnetide#272]
Step to reproduce: set your Windows to scale the screen to 125%.

What you see: only the text editor area of PascalABC.NET is scaled according to the setting, the rest of the UI don't.

What you expect: everything scaled according to the setting.

**Comment by SunSerega** [comment]
A few years ago there was someone else who (with system scaling or something else, idk) managed to scale UI for his 4k monitor and was then consistently reporting bugs...
What system are you on? There are separate editors for Linux and for Windows.
What methods did you try to make UI (not just text area) scale?

**Comment by ghost** [comment]
> What system are you on? There are separate editors for Linux and for Windows. What methods did you try to make UI (not just text area) scale?

Windows 8.1 64 bit. Using the setting on Display of Control Panel to scale my screen to 125%. I found only the text area of the IDE scaled, the rest of the UI remain unchanged. Is it clear enough to you? Btw, why don't you go and try it yourself? Scale your screen to 125% and test the PascalABC.NET IDE.

p/s: I'm sure there is nothing wrong with my settings. It's not the first day I'm using a computer. I correctly set all items on the screen to be scaled to 125%. Other applications, including Java based ones, correctly followed the scaling setting.

**Comment by miks1965** [comment]
All is OK. This is the result of 250% scaling. PascalABC.NET follows HIGH DPI Scaling with some minor inaccuracies
![изображение](https://github.com/pascalabcnet/pascalabcnetide/assets/10325391/3981ccd0-76f8-4e0b-9924-dc97ca840a3d)

**Comment by ghost** [comment]
> All is OK. This is the result of 250% scaling. PascalABC.NET follows HIGH DPI Scaling with some minor inaccuracies ![изображение](https://user-images.githubusercontent.com/10325391/248862167-3981ccd0-76f8-4e0b-9924-dc97ca840a3d.png)

Why you are so keen at closing issues? You are just confirmed what I said. Only the text editor area follows the scaling setting. The rest of the UI don't. It's indeed these `some minor inaccuracies` are what I wanted to be fixed. Other applications, including Java based ones have no problems with following the scaling setting.

**Comment by miks1965** [comment]
I dont see any inaccuracies on my screenshot. Please publish yours

**Comment by ghost** [comment]
> I dont see any inaccuracies on my screenshot. Please publish yours

I already uploaded on https://github.com/pascalabcnet/pascalabcnetide/issues/273
