### ISSUE TITLE
string + uint64, string + cardinal работает неправильно

### ISSUE THREAD

**Issue by avkw1** [pascalabcnet/pascalabcnetide#287]
Операция + для строки и целого числа всегда преобразует число в int32.
Не знаю, баг это или нет, однако работает не так, как ожидалось, легко сделать ошибку.
Чтобы получилось правильно, нужно добавлять .ToString.
Пример кода:
```
program bug_string_uint64;

var
  x: uint64;
  y: cardinal;
  s: string;

begin
  x := 123456789012345;
  s := 'x = ' + x;  // x.ToString
  writeln(s);
  y := 4000000000;
  s := 'y = ' + y;  // y.ToString
  writeln(s);
end.
```

**Comment by SunSerega** [comment]
Да, сейчас оператор сложения со строкой перегружен только для `integer`, это создаёт не интуитивное поведение...

**Comment by SunSerega** [comment]
Только вы не туда issue залили. Это репозиторий для issue IDE - а ваша проблема проявляется и без IDE, даже если консольный компилятор использовать. Значит её надо в основной репозиторий.

**Comment by SunSerega** [comment]
> только для `integer`

Поправка - ещё для `real`: https://github.com/pascalabcnet/pascalabcnet/blob/master/bin/Lib/PABCSystem.pas#L4243

**Comment by avkw1** [comment]
Я извиняюсь, немного перепутал. Как-то можно перенести в основной репозиторий?

**Comment by avkw1** [comment]
Создал в основном репозитории
https://github.com/pascalabcnet/pascalabcnet/issues/2985
