### ISSUE TITLE
Анализатор кода не подставляет тип параметра лямбды, если это не метод расширения

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#54]
```
begin
  var l := new List<byte>;
  l.RemoveAll(b->b=1);
end.
```
При наведении на `b` в лямбде показывает `b: T` вместо `b: byte`.

Вроде в 1 из последних билдов это ещё работало нормально.
По крайней мере у меня есть код, написание которого без анализатора кода было бы ужасным мучением. И вот я не помню этих мучений.

**Comment by ibond84** [comment]
у меня показывает byte
