### ISSUE TITLE
Анализатор кода не правильно понимает foreach для SortedDictionary.Values 

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#70]
```
begin
  var d: SortedDictionary<byte, word>;
  foreach var v in d.Values do
end.
```
Для `v` показывает тип `byte`, вместо `word`.

Это не дубль #894. Та ошибка касается всех наследников `IDictionary`, а эта только `SortedDictionary`.

**Comment by ibond84** [comment]
Исправлено в семантическом интеллисенсе
