### ISSUE TITLE
Анализатор кода игнорирует явно указанные шаблонные параметры

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#71]
```
type
  ft=()->integer;

begin
  var f:ft := ()->0;
  var a := Arr(0).Select&<integer,ft>(i->f);
end.
```
Тут для `a` показывает тип `sequence of integer`, хотя он `sequence of ft`.

Если шаблонные параметры указаны напрямую, через `&<>` - смотреть на содержимое функции вообще не надо. Если оставить так - будет, наверняка, на много больше ошибок.

**Comment by ibond84** [comment]
Исправлено в семантическом интеллисенсе
