### ISSUE TITLE
Анализатор кода неправильно понимает лямбду, когда тип входных параметров или возвращаемое значение - кортеж

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#78]
Если 1 из входных параметров кортеж:
```
begin
  var a: sequence of (byte, word);
  var b := a.Select(t -> 0);//   "(t,i) -> 0"   точно так же сломан
end.
```
Тут для `b` показывает тип `sequence of Tuple(byte,word)`.

Если возвращаемое значение кортеж - тоже:
```
begin
  var a := Arr(1, 3, 5).Select(i -> (i, i))
end.
```
Тут для `a` показывает тип `sequence of integer`.

**Comment by ibond84** [comment]
Работает с опцией "использовать компилятор для intellisense" (семантический интеллисенс)
