### ISSUE TITLE
Скобочки в отдельных строках подсвечиваются

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnetide#92]
```
begin
  var s1 := '(';
  var s2 := ')';
end.
```
![image](https://user-images.githubusercontent.com/27270190/45540262-a01e5800-b814-11e8-8b55-9cee54ccaccf.png)

Это ведь уже исправляли, разве нет? Может стоит сделать тесты на это?

**Comment by ibond84** [comment]
мелочь, которая трудно исправляется. отклоняю
